#pubspec.yaml
name: Serviscribe
description: "AI app for car service records"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.0
  path: ^1.9.0
  http: ^1.2.1
  logging: ^1.2.0
  provider: ^6.1.2
  go_router: ^16.2.0
  path_provider: ^2.1.3
  permission_handler: 12.0.1
  camera: ^0.11.0+1
  image: ^4.5.4
  printing: ^5.12.0
  image_picker: 1.2.0
  file_picker: ^10.3.2
  image_cropper: 9.1.0
  flutter_image_compress: 2.4.0
  amplify_flutter: ^2.2.0
  amplify_storage_s3: ^2.2.0
  amplify_auth_cognito: ^2.6.5
  amplify_secure_storage: ^0.5.12
  amplify_analytics_pinpoint: ^2.6.5
  amplify_secure_storage_dart: ^0.5.7  # --------------------------------

  syncfusion_flutter_pdf: 30.1.39
  syncfusion_flutter_pdfviewer: ^30.1.39

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true


